#!/usr/bin/env sh
d="manual_pydabu_html"
if [ ! -d $d ]; then
    mkdir $d
fi

skipcp='false'
if [ ! $# -eq 0 ]; then
    if [ 'skipcp' = $1 ]; then
	skipcp='true'
    fi
fi
if [ $skipcp != "true" ]; then
    cp -p README.md INSTALL.txt doc/source/
fi

if [ -d coverage_report ]; then
    cp -p coverage_report/index.html doc/source/test_coverage_report/
fi

cd doc
make html
if [ $? -eq 0 ]; then
    rsp="--archive --one-file-system --links --hard-links --sparse --checksum"
    bhp="build/html"
    dd="$d/test_coverage_report"
    rsync --delete-after $rsp $bhp/ ../$d/
    if [ -d ../coverage_report ]; then
	rsync --delete-after $rsp  ../coverage_report/ ../$dd/
	cp -p $bhp/test_coverage_report/index.html ../$dd/index.html
    fi
fi
cd ..
