#!/usr/bin/env bash
set -e
cp -p README.md doc/source/ || exit $?
# build all documentation formats in parallel
./create_doc_pdf skipcp &
pid1=$!
./create_doc_html skipcp &
pid2=$!
wait $pid1 $pid2 && echo -e "\n+-------+\n| ready |\n+-------+"
