#!/bin/sh -l
set -e -x
date

echo "#######################"

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -q -y latexmk libudunits2-0 lsb-release python3-jsonschema python3-netcdf4 python3-pip python3-pytest python3-pytest-cov python3-pytest-xdist python3-recommonmark python3-setuptools python3-sphinx python3-sphinx-argparse python3-wheel texlive-fonts-recommended texlive-latex-extra texlive-latex-recommended
DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -q -y libudunits2-0 lsb-release python3-jsonschema python3-netcdf4 python3-pip python3-pytest python3-pytest-cov python3-pytest-xdist python3-setuptools python3-wheel

echo "#######################"

uname -a
dpkg --print-architecture
lsb_release -a
lscpu
env python3 -V
cat /etc/os-release

echo "#######################"

pip3 install cfchecker
env python3 setup.py check_modules
pip3 install .

echo "#######################"

which pydabu
pydabu
which json_schema_from_schema_org
json_schema_from_schema_org -h

echo "#######################"

env python3 setup.py run_unittest
env python3 setup.py run_pytest --parallel --coverage
